---
#roles/logstash/main.yml

- name: "check if logstash is installed"
  shell: logstash --version
  become: true
  register: logstash_result
  ignore_errors: true
  tags:
    - logstash

- name: "dowload and install logstash"
  shell: |
    cd /tmp 
    wget https://artifacts.elastic.co/downloads/logstash/logstash-7.5.0.deb
    wget https://artifacts.elastic.co/downloads/logstash/logstash-7.5.0.deb.sha512
    shasum -a 512 -c logstash-7.5.0.deb.sha512  
    sudo dpkg -i logstash-7.5.0.deb
  become: true 
  ignore_errors: true
  when: logstash_result is failed
  tags:
    - logstash

- name: "configure logstash"
  template:
    src:  logstash.yml.j2
    dest: /etc/logstash/logstash.yml
  become: true
  notify:
    - restart logstash
  tags:
    - logstash
    - lconfigure

- name: "configure logstash pipelines"
  template:
    src:  pipelines.yml.j2
    dest: /etc/logstash/pipelines.yml
  become: true
  notify:
    - restart logstash
  tags:
    - logstash
    - lconfigure

- name: "configure logstash jvm options"
  template:
    src: jvm.options.j2
    dest: /etc/logstash/jvm.options
  become: true
  notify:
    - restart logstash
  tags:
    - logstash
    - jvmoptions

- name: "logstash startup script"
  shell:
    chdir: /usr/share/logstash/bin 
    cmd: ./system-install
  when: logstash_result is failed
  become: true
  tags:
    - logstash
    - linstall