---
# roles/elasticsearch/main.yml

- name: "check for elasticsearch rpm file"
  stat:
    path: /tmp/elasticsearch-7.4.2.rpm
  register: stat_result
  tags:
    - elastic
    - edownload

- name: "download elasticsearch rpm"
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.4.2-x86_64.rpm
    dest: /tmp/elasticsearch-7.4.2.rpm
  register: download_stat
  until: download_stat is not failed
  when: stat_result.stat.exists == False
  become: true
  tags:
    - elastic
    - edownload

- name: "check for elasticsearch install directory"
  stat:
    path: /etc/elasticsearch/elasticsearch.yml
  register: stat_result
  tags:
    - elastic
    - einstall

- name: "install elasticsearch"
  yum:
    name: /tmp/elasticsearch-7.4.2.rpm
    state: present
  when: stat_result.stat.exists == False
  become: true
  tags:
    - elastic
    - einstall

- name: "configure elasticsearch"
  template:
    src:  elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  become: true
  notify:
    - restart elasticsearch
  tags:
    - elastic
    - econfigure

- name: "configure elasticsearch jvm options"
  template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options
  become: true
  notify:
    - restart elasticsearch
  tags:
    - elastic
    - jvmoptions
