---
# roles/filebeat/task/main.yml

# roles/filebeat/task/main.yml

- name: "check if filebeat is installed"
  shell: elasticsearch --version
  become: True
  register: filebeat_result
  ignore_errors: True
  tags:
    - filebeat

- name: "dowload and install filebeat"
  shell: |
    cd /tmp 
    wget https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.5.0-amd64.deb
    wget https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.5.0-amd64.deb.sha512
    shasum -a 512 -c filebeat-7.5.0-amd64.deb.sha512  
    sudo dpkg -i filebeat-7.5.0-amd64.deb
  become: true
  when: filebeat_result is failed
  tags:
    - filebeat

#- name: "configure filebeat"
#  template:
#    src:  filebeat.yml.j2
#    dest: /etc/filebeat/filebeat.yml
#  become: true
#  notify:
#    - restart filebeat
#  tags:
#    - filebeat
#    - fconfigure
